### PR TITLE
cli: support multiple words

### LINKED ISSUE #308: [feature] Support multiple words
Such as:

```sh
$ pypinyin -sz 你好 您好
nh
nh
```

### PR DESCRIPTION
**Pull request by Freed-Wu**
- Fix #308, support multiple words
- Use github in pre-commit

## 待办事项

* [x] 符合代码规范
* [x] 单元测试
* [x] 文档

### CODE REVIEW

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Comment by Freed-Wu** [comment]
- Can you publish a new version to let me enjoy new version?
- Can you add me to collabrotors?

**Comment by mozillazg** [comment]
我争取这周末的时候发一个新版本。

**Comment by mozillazg** [comment]
新版本已发布。

**Pull request merged**
