### PR TITLE
Added CYRILLIC pinyin style

### PR DESCRIPTION
**Pull request by tyrbonit**
Added new pinyin styles - CYRILLIC (汉语拼音与俄语字母对照表) and CYRILLIC _FIRST, russian translate documentation

### CODE REVIEW

**Comment by mozillazg** [comment]
Thanks! Please fix the CI error and add tests for these features.

**Comment by tyrbonit** [comment]
Complete! The CI error is fixed and tests added.

**Comment by mozillazg** [comment]
@tyrbonit Thank You!

**Comment by Artoria2e5** [comment]
> 汉语拼音与俄语字母对照表

Wait, wait, is this like referenced at all? I guess it's time to add something more formal (Хуэйзў йүян, شِيَوْ عَر دٍ)...

**Pull request merged**
